// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttiqbrwvbppcjlsiopea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0aXFicnd2YnBwY2psc2lvcGVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzODk5NDksImV4cCI6MjA1MDk2NTk0OX0.v7yMLwQYsom_p4lstkfDTl4sg6GbYzmcyyXsYp5uc3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);